service: opencv2-lambda-layer
frameworkVersion: ">=1.34.0 <2.0.0"
provider:
  name: aws
layers:
  opencv2python37:
    path: layers/3.7
  opencv2python38:
    path: layers/3.8
resources:
  Outputs:
    Opencv237LambdaLayerExport:
      Value:
        Ref: Opencv2python37LambdaLayer
      Export:
        Name: OpenCV2Python37LambdaLayer
    Opencv238LambdaLayerExport:
      Value:
        Ref: Opencv2python38LambdaLayer
      Export:
        Name: OpenCV2Python38LambdaLayer